[package]
name = "rexds"
version = "0.4.32"
edition = "2021" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.17"
tokio = { version = "1.25.0", features = ["full"] }
hyper = { version = "0.14.26", features = ["full"] }
