name: Build & Release - All supported platforms

on:
  push:
    tags:
      - '*'

jobs:
  job_1:
    name: Linux X86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - shell: bash
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
      - name: Results
        uses: actions/upload-artifact@v3
        with:
          name: Linux-X86_64
          path: target/x86_64-unknown-linux-gnu/release/rexds
  
  job_2:
    name: Linux ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - shell: bash
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu
      - name: Results
        uses: actions/upload-artifact@v3
        with:
          name: Linux-ARM64
          path: target/aarch64-unknown-linux-gnu/release/rexds

  job_3:
    name: Windows X86_64
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - shell: bash
        run: |
          cargo build --release --target x86_64-pc-windows-msvc
      - name: Results
        uses: actions/upload-artifact@v3
        with:
          name: Windows-X86_64
          path: target/x86_64-pc-windows-msvc/release/rexds.exe

  job_4:
    name: macOS X86_64
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - shell: bash
        run: |
          cargo build --release --target x86_64-apple-darwin 
      - name: Results
        uses: actions/upload-artifact@v3
        with:
          name: macOS-X86_64
          path: target/x86_64-apple-darwin/release/rexds

  job_5:
    uses: actions/checkout@v3
    name: macOS ARM64
    runs-on: macOS-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - shell: bash
        run: |
          cargo build --release --target aarch64-apple-darwin
      - name: Results
        uses: actions/upload-artifact@v3
        with:
          name: macOS-ARM64
          path: target/aarch64-apple-darwin/release/rexds
